CREATE TABLE inquiries (
    id VARCHAR(255) PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    service_type VARCHAR(255) NOT NULL,
    event_date DATE,
    date_preference VARCHAR(255),
    venue VARCHAR(255),
    message VARCHAR(2000),
    package_name VARCHAR(255),
    source_page VARCHAR(255),
    status VARCHAR(40) NOT NULL,
    admin_notes VARCHAR(2000),
    submitted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_inquiries_status CHECK (status IN (
        'NEW', 'CONTACTED', 'CONSULTATION_BOOKED', 'QUOTE_SENT',
        'BOOKED', 'NOT_PROCEEDING', 'COMPLETED', 'ARCHIVED'
    ))
);

CREATE INDEX idx_inquiries_status_submitted ON inquiries (status, submitted_at DESC);
CREATE INDEX idx_inquiries_event_date ON inquiries (event_date);
CREATE INDEX idx_inquiries_service_type ON inquiries (service_type);

CREATE TABLE stored_assets (
    asset_key VARCHAR(255) PRIMARY KEY,
    original_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    size_bytes BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    content BYTEA NOT NULL,
    CONSTRAINT ck_stored_assets_size CHECK (size_bytes >= 0)
);

CREATE INDEX idx_stored_assets_created ON stored_assets (created_at);

CREATE TABLE inquiry_attachments (
    inquiry_id VARCHAR(255) NOT NULL,
    asset_key VARCHAR(255) NOT NULL,
    CONSTRAINT fk_inquiry_attachments_inquiry
        FOREIGN KEY (inquiry_id) REFERENCES inquiries (id) ON DELETE CASCADE
);

CREATE INDEX idx_inquiry_attachments_inquiry ON inquiry_attachments (inquiry_id);

CREATE TABLE reviews (
    id VARCHAR(255) PRIMARY KEY,
    reviewer_name VARCHAR(255) NOT NULL,
    reviewer_role VARCHAR(255),
    ceremony_type VARCHAR(255) NOT NULL,
    rating INTEGER NOT NULL,
    headline VARCHAR(255),
    message VARCHAR(2000) NOT NULL,
    event_date DATE,
    status VARCHAR(40) NOT NULL,
    moderation_note VARCHAR(255),
    submitted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    moderated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_reviews_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT ck_reviews_status CHECK (status IN ('PENDING', 'APPROVED', 'DISABLED', 'REJECTED'))
);

CREATE INDEX idx_reviews_status_submitted ON reviews (status, submitted_at DESC);
CREATE INDEX idx_reviews_ceremony_type ON reviews (ceremony_type);

CREATE TABLE review_photos (
    review_id VARCHAR(255) NOT NULL,
    asset_key VARCHAR(255) NOT NULL,
    CONSTRAINT fk_review_photos_review
        FOREIGN KEY (review_id) REFERENCES reviews (id) ON DELETE CASCADE
);

CREATE INDEX idx_review_photos_review ON review_photos (review_id);

CREATE TABLE analytics_daily_visits (
    visit_date DATE PRIMARY KEY,
    visit_count BIGINT NOT NULL,
    CONSTRAINT ck_daily_visits_count CHECK (visit_count >= 0)
);

CREATE TABLE analytics_funnel_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(255) NOT NULL,
    page_path VARCHAR(255),
    service_type VARCHAR(255),
    package_name VARCHAR(255),
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_funnel_event_type_recorded ON analytics_funnel_events (event_type, recorded_at DESC);
CREATE INDEX idx_funnel_page_path ON analytics_funnel_events (page_path);
CREATE INDEX idx_funnel_service_type ON analytics_funnel_events (service_type);
CREATE INDEX idx_funnel_package_name ON analytics_funnel_events (package_name);
